version: '3'
services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    restart: always

volumes:
  frontend:
  backend:
